### ISSUE TITLE
Intermittent IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by acutetech** [kizitonwose/CalendarView#21]
I see the following error intermiitently as I start an activity which creates and renders a calendar.  I have seen Index:7 as well as 14, but no other numbers. I am using v0.2.0

I create and render a calendar, then request data from a database and when it arrives I call the calendar's setup() again (different months to display), and paint the day cells again depending on the data. If I add a short delay c. 200ms before making the database call then the fault does not occur, so I am guessing the second setup() is messing with the first.

So I guess the questions are:
(1) What is causing the crash and can it be stopped?
(2) Is it OK to call setup() twice, or is there a better way to change the first and last month values dynamically?
(3) Is there a "onCalendarReady()" callback, or similar, which I can wait for before making my second setup() call? use to make changes?

Error log:

    java.lang.IndexOutOfBoundsException: Index: 14, Size: 4
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.notifyMonthScrollListenerIfNeeded(CalendarAdapter.kt:171)
        at com.kizitonwose.calendarview.ui.CalendarAdapter$notifyMonthScrollListenerIfNeeded$1.onAnimationsFinished(CalendarAdapter.kt:165)
        at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationsFinished(RecyclerView.java:13257)
        at androidx.recyclerview.widget.DefaultItemAnimator.dispatchFinishedWhenDone(DefaultItemAnimator.java:551)
        at androidx.recyclerview.widget.DefaultItemAnimator$5.onAnimationEnd(DefaultItemAnimator.java:249)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1142)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:905)
        at android.view.Choreographer.doCallbacks(Choreographer.java:709)
        at android.view.Choreographer.doFrame(Choreographer.java:641)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:6304)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by kizitonwose** [comment]
It's okay to call `setup()` repeatedly. However, I can confirm that calling `setup()` successively without a delay causes this error. I'll further investigate this issue and see why this is happening.

**Comment by ashleymorris2** [comment]
I'm getting this issue on 0.3.2
