### ISSUE TITLE
null casting to CalendarAdapter

### ISSUE THREAD

**Issue by BobNies** [kizitonwose/CalendarView#210]
This started showing up after updating to 0.4.3

2020-09-01 14:49:53.070 22099-22099/com.movemedical.movemobile E/Logger: scheduleAdapter
    kotlin.TypeCastException: null cannot be cast to non-null type com.kizitonwose.calendarview.ui.CalendarAdapter
        at com.kizitonwose.calendarview.CalendarView.getCalendarAdapter(CalendarView.kt:481)
        at com.kizitonwose.calendarview.CalendarView.notifyDayChanged(CalendarView.kt:671)
        at com.kizitonwose.calendarview.CalendarView.notifyDateChanged(CalendarView.kt:679)
        at com.kizitonwose.calendarview.CalendarView.notifyDateChanged$default(CalendarView.kt:678)
        at com.movemedical.movemobile.ui.schedule.ScheduleFragment.selectCalendarDate(ScheduleFragment.kt:515)
        at com.movemedical.movemobile.ui.schedule.ScheduleFragment.access$selectCalendarDate(ScheduleFragment.kt:64)
        at com.movemedical.movemobile.ui.schedule.ScheduleFragment$initAdapter$$inlined$with$lambda$1.onScrolled(ScheduleFragment.kt:491)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5268)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4326)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3952)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4499)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
        at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
        at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
2020-09-01 14:49:53.070 22099-22099/com.movemedical.movemobile E/Logger:     at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1062)
        at android.view.View.layout(View.java:23753)
        at android.view.ViewGroup.layout(ViewGroup.java:7277)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3679)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3139)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by kizitonwose** [comment]
Odd, before calling `notifyDayChanged`, the calendar must have been setup. Can you consistently reproduce this?

**Comment by fromdestiny** [comment]
I have same issue.  When I called "setupAsync", error occurred. 
kotlin.TypeCastException: null cannot be cast to non-null type com.kizitonwose.calendarview.ui.CalendarAdapter
        at com.kizitonwose.calendarview.CalendarView.getCalendarAdapter(CalendarView.kt:481)
        at com.kizitonwose.calendarview.CalendarView.getMonthUpdateData(CalendarView.kt:888)
        at com.kizitonwose.calendarview.CalendarView.access$getMonthUpdateData(CalendarView.kt:27)
        at com.kizitonwose.calendarview.CalendarView$updateMonthRangeAsync$1.invokeSuspend(CalendarView.kt:877)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

It's not always shown, but quite many time it happened. so I changed "setupAsync" -> "setup", until now it's gone.

**Comment by BobNies** [comment]
Happens every time i load my fragment.

**Comment by kizitonwose** [comment]
Are you calling `setup()` or `setupAsync()` ?

**Comment by kizitonwose** [comment]
Sorry, I just saw in @fromdestiny's comment that you were both calling `setupAsync()`. 

The `setupAsync()` method allows you to pass a completion block which is called after setup is done. Only then should you call other methods on the view.

Simply put, when using `setupAsync()`, every other initial method calls(scrollToMonth(), notifyDateChanged() etc) should be moved into the completion block.

Examples:

This will crash:
```kotlin
val currentMonth = YearMonth.now()
val startMonth = currentMonth.minusMonths(10)
val endMonth = currentMonth.plusMonths(10)
calendarView.setupAsync(startMonth, endMonth, daysOfWeek.first()) // Note: setupAsync(), not setup()
calendarView.scrollToMonth(currentMonth) // This is not legal and will crash.
```

This will not crash:

```kotlin
val currentMonth = YearMonth.now()
val startMonth = currentMonth.minusMonths(10)
val endMonth = currentMonth.plusMonths(10)
calendarView.setupAsync(startMonth, endMonth, daysOfWeek.first()) {
    calendarView.scrollToMonth(currentMonth) // This is legal and will NOT crash.
}
```

The only resolution I see here is clarifying the documentation for `setupAsync()` to inform users to use the completion block.

Closing this as it's working as expected, please leave a comment if you need anything else.

**Comment by DJDrama** [comment]
Having Same problem and hmm your solution does not work :-(
