### ISSUE TITLE
Error inflating class android.view.View

### ISSUE THREAD

**Issue by alahdal** [kizitonwose/CalendarView#220]
Thank you for the work.

I have tested the app with a Huawei Media tablet (couple of years old) and it works fine, however, when I tried to install it on Samsung Note 3, I get the below error. If I comment everything related to the calendar inside the respective fragment, the app is installed without problem.

`09-24 22:28:09.615 4264-4264/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 4264
    android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class android.view.View
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.kizitonwose.calendarview.utils.ExtensionsKt.inflate(Extensions.kt:14)
        at com.kizitonwose.calendarview.utils.ExtensionsKt.inflate$default(Extensions.kt:13)
        at com.kizitonwose.calendarview.ui.DayHolder.inflateDayView(DayHolder.kt:26)
        at com.kizitonwose.calendarview.ui.WeekHolder.inflateWeekView(WeekHolder.kt:22)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.onCreateViewHolder(CalendarAdapter.kt:91)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.onCreateViewHolder(CalendarAdapter.kt:31)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7216)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6347)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6231)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6227)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4230)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3630)
        at com.kizitonwose.calendarview.CalendarView.onMeasure(CalendarView.kt:300)
        at android.view.View.measure(View.java:18797)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:763)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:426)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:105)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:247)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:117)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1532)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1607)
        at android.view.View.measure(View.java:18797)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:18797)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
        at android.view.View.measure(View.java:18797)
        at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
        at android.view.View.measure(View.java:18797)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:18797)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
        at android.view.View.measure(View.java:18797)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
    	at android.widget.FrameLayout.onMeasure(FrameLayout.j`

**Comment by alahdal** [comment]
I updated the phone using LineageOS 16 (Android 9) and it works fine. The Huawei Media is running Android 7. Hence, I can conclude that the CalendarView has problem with less than Android 7.

**Comment by kizitonwose** [comment]
The minSDK is 15, I suspect you have an issue with setting up Desugar but that is something I may not be able to help you with considering that I don't know what setup you have.
