### ISSUE TITLE
Problem with setupAsync

### ISSUE THREAD

**Issue by emiliodonaire** [kizitonwose/CalendarView#271]
java.lang.NoSuchMethodError: No virtual method getMonthValue()I in class Lj$/time/YearMonth; or its super classes (declaration of 'j$.time.YearMonth'
com.kizitonwose.calendarview.model.MonthConfig$Companion.generateWeekDays$com_github_kizitonwose_CalendarView(MonthConfig.kt:185)
                at com.kizitonwose.calendarview.model.MonthConfig$Companion.generateBoundedMonths(MonthConfig.kt:57)
                at com.kizitonwose.calendarview.model.MonthConfig.<init>(MonthConfig.kt:23)
                at com.kizitonwose.calendarview.CalendarView$setupAsync$1.invokeSuspend(CalendarView.kt:700)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by kizitonwose** [comment]
It's the same issue as #249

**Comment by kizitonwose** [comment]
I'll close this since the other one is already open.
