### ISSUE TITLE
Week mode calendar crashes when orientation changes

### ISSUE THREAD

**Issue by Amunak** [kizitonwose/CalendarView#29]
Steps to reproduce in the sample app:

1. Allow orientation changes by removing the forced `screenOrientation` attribute from the app's Manifest for the main Activity.
0. Run the app and open "Example 7".
0. Scroll to the right by about a month or more.
0. Change the device's orientation.

The app should crash with this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kizitonwose.calendarviewsample, PID: 10788
    kotlin.TypeCastException: null cannot be cast to non-null type com.kizitonwose.calendarview.ui.MonthViewHolder
        at com.kizitonwose.calendarview.ui.CalendarLayoutManager$scrollToDay$1.run(CalendarLayoutManager.kt:51)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Apparently, this

>We already scrolled to this position so findViewHolder should not return null.

is not really true 😕. I assume it has something to do with restarting the activity, though I don't see why or how. Probably something to do with the fact that WeekMode doesn't really have MonthViewClass (or whatever it's called) and there isn't a proper check there.

I've found out that it happens inconsistently - you have to scroll by quite a bit, but some times (I think) less than other times. Oh and it happens when scrolling to the left, too.

**Comment by kizitonwose** [comment]
Thank you for reporting this issue. Solved it by always treating the ViewHolder as nullable.
