### ISSUE TITLE
Crash when we scroll the month view fast back & forth 

### ISSUE THREAD

**Issue by dpk21011991** [kizitonwose/CalendarView#320]
My month calendar has events and they're generated using an api call on month scroll

```
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling com.kizitonwose.calendarview.CalendarView{a07681a VFED..... ......ID 0,50-1080,830 #7f0a04c7 

adapter:com.kizitonwose.calendarview.ui.CalendarAdapter@4fb6f4b, layout:com.kizitonwose.calendarview.ui.CalendarLayoutManager@9f96d28,

at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3185)
at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:5712)
at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:12674)
at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:7626)
at com.kizitonwose.calendarview.ui.CalendarAdapter.reloadDay(CalendarAdapter.kt:165)
at com.kizitonwose.calendarview.CalendarView.notifyDayChanged(CalendarView.kt:577)
at com.kizitonwose.calendarview.CalendarView.notifyDateChanged(CalendarView.kt:585)
at com.kizitonwose.calendarview.CalendarView.notifyDateChanged$default(CalendarView.kt:584)
at com.kizitonwose.calendarview.CalendarView.notifyDateChanged(CalendarView.kt)

at com.kizitonwose.calendarview.ui.CalendarAdapter.notifyMonthScrollListenerIfNeeded(CalendarAdapter.kt:201)
at com.kizitonwose.calendarview.ui.CalendarAdapter$notifyMonthScrollListenerIfNeeded$1.onAnimationsFinished(CalendarAdapter.kt:191)
at androidx.recyclerview.widget.RecyclerView$ItemAnimator.dispatchAnimationsFinished(RecyclerView.java:13751)
at androidx.recyclerview.widget.DefaultItemAnimator.dispatchFinishedWhenDone(DefaultItemAnimator.java:551)
at androidx.recyclerview.widget.DefaultItemAnimator$4.onAnimationEnd(DefaultItemAnimator.java:215)
at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1121)
at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1167)
at android.animation.ValueAnimator.cancel(ValueAnimator.java:1057)
at android.view.ViewPropertyAnimator.cancel(ViewPropertyAnimator.java:427)
at androidx.recyclerview.widget.DefaultItemAnimator.endAnimation(DefaultItemAnimator.java:439)
at androidx.recyclerview.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:526)
at androidx.recyclerview.widget.DefaultItemAnimator.animateRemove(DefaultItemAnimator.java:193)
at androidx.recyclerview.widget.SimpleItemAnimator.animateDisappearance(SimpleItemAnimator.java:107)
at androidx.recyclerview.widget.RecyclerView.animateDisappearance(RecyclerView.java:4547)
at androidx.recyclerview.widget.RecyclerView$4.processDisappeared(RecyclerView.java:648)
at androidx.recyclerview.widget.ViewInfoStore.process(ViewInfoStore.java:232)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4378)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4031)
at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2017)
at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
at android.view.Choreographer.doCallbacks(Choreographer.java:699)
at android.view.Choreographer.doFrame(Choreographer.java:631)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6349)
at java.lang.reflect.Method.invoke(Native Method)
2021-07-05 18:11:06.605 1728-1728/? E/JobServiceContext: Time-out while trying to bind b745e1f #u0a273/477639694 com.coffeeenterprise.test/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService, dropping.
```

**Comment by kizitonwose** [comment]
I don't fully understand what you're trying to do that caused the crash, could you explain more?

**Comment by danielcerezodev** [comment]
If you could post part of your source could I could help you out. I have encountered this, but your use case might be different.
