### ISSUE TITLE
KotlinNullPointerException

### ISSUE THREAD

**Issue by EgorThe1st** [kizitonwose/CalendarView#43]
Hi, thank's for great lib. However, I faced the issue: crash when first open a fragment with calendar view. It happened once, and I think the problem is in using unsafe (!!) call.

```
kotlin.KotlinNullPointerException
        at com.kizitonwose.calendarview.ui.MonthViewHolder.bindMonth(MonthViewHolder.kt:39)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.onBindViewHolder(CalendarAdapter.kt:144)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.onBindViewHolder(CalendarAdapter.kt:27)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7033)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.onBindViewHolder(CalendarAdapter.kt:135)
        at com.kizitonwose.calendarview.ui.CalendarAdapter.onBindViewHolder(CalendarAdapter.kt:27)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7075)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5991)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6258)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6097)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6093)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4115)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3832)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4385)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6202)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6202)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20715)
        at android.view.ViewGroup.layout(ViewGroup.java:6202)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:444)


```

**Comment by EgorThe1st** [comment]
Here is the initialization:

```
 class DateSelectFragment : BaseFragment(), DateSelectView {

    companion object {
        fun newInstance(): DateSelectFragment = DateSelectFragment()
    }

    private val today =org.threeten.bp.LocalDate.now()

    private val dayBinder = getDayBinder()


    @InjectPresenter
    lateinit var presenter: DateSelectPresenter

    override fun getLayoutRes() = R.layout.fragment_date_select

    override fun initUI() {
        super.initUI()

    
        Handler().post { initCalendarView() }
    }

    private fun initCalendarView() {
        date_select_calendar_view.dayBinder = dayBinder

        date_select_calendar_view.monthFooterBinder = object : MonthHeaderFooterBinder<MonthFooterContainer> {
            override fun create(view: View) = MonthFooterContainer(view)

            override fun bind(container: MonthFooterContainer, month: CalendarMonth) {
            }
        }

        date_select_calendar_view.monthHeaderBinder = object : MonthHeaderFooterBinder<MonthHeaderContainer> {

            override fun create(view: View) = MonthHeaderContainer(view)

            override fun bind(container: MonthHeaderContainer, month: CalendarMonth) {
                container.monthTitle.text = month.yearMonth.format(DateTimeFormatter.ofPattern("MMM yyyy"))
            }
        }
        val currentMonth = YearMonth.now()
        val lastMonth = currentMonth.plusMonths(12)
        val firstDayOfWeek = WeekFields.of(Locale.getDefault()).firstDayOfWeek

        date_select_calendar_view.setup(currentMonth, lastMonth, firstDayOfWeek)
    }

    class DayViewContainer(view: View) : ViewContainer(view) {
        val textView = view.calendar_day_text
    }

    class MonthHeaderContainer(view: View) : ViewContainer(view) {
        val monthTitle = view.calendar_month_title
    }

    class MonthFooterContainer(view: View) : ViewContainer(view)

    private fun getDayBinder(): DayBinder<DayViewContainer> {

        return object : DayBinder<DayViewContainer> {

            // Called only when a new container is needed.
            override fun create(view: View) = DayViewContainer(view)

            // Called every time we need to reuse a container.
            override fun bind(container: DayViewContainer, day: CalendarDay) {
                val dayText = container.textView

                fun setStandartDayColor() {
                    dayText.textColor = ContextCompat.getColor(requireContext(), R.color.blue_primary)
                }

                fun setInactiveDayColor() {
                    dayText.textColor = ContextCompat.getColor(requireContext(), R.color.calendar_inactive_date)
                }

                fun setFullSelectedDayView() {
                    dayText.textColor = ContextCompat.getColor(requireContext(), R.color.white)
                    dayText.background = resources.getDrawable(R.drawable.bg_calendar_selected_day_full, null)
                }

                fun clearTextBackground() {
                    dayText.background = null
                }

                fun setInitialState() {
                    dayText.text = null
                    setStandartDayColor()
                    clearTextBackground()
                }

                setInitialState()

                if (day.owner == DayOwner.THIS_MONTH) {
                    dayText.text = day.day.toString()

                    if (day.date.isBefore(today)) setInactiveDayColor()

                    if (!day.date.isBefore(today) && !day.date.isAfter(today)) {
                        setFullSelectedDayView()
                    }

                }

            }
        }
    }
}
```

Is it correct?

**Comment by kizitonwose** [comment]
> Is it correct?

Yes, that should work.

**Comment by kizitonwose** [comment]
Is the issue fixed for you? Can I close this now?

**Comment by EgorThe1st** [comment]
> Is the issue fixed for you? Can I close this now?

Yes, I guess
