### ISSUE TITLE
Sample app crashes since v0.2.6

### ISSUE THREAD

**Issue by VarHastra** [kizitonwose/CalendarView#44]
Steps to reproduce the issue:

1. Run the sample app and open Example 1.
2. Click the Week mode checkbox to collapse the calendar.
3. Click the Week mode checkbox one more time to expand the calendar.

After that the app should crash with the following stacktrace:

```
08-22 21:08:42.318 32144-32144/com.kizitonwose.calendarviewsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kizitonwose.calendarviewsample, PID: 32144
    java.lang.IndexOutOfBoundsException: Invalid index 42, size is 16
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.kizitonwose.calendarview.CalendarView.updateAdapterMonthConfig(CalendarView.kt:412)
        at com.kizitonwose.calendarview.CalendarView.updateAdapterMonthConfig$default(CalendarView.kt:406)
        at com.kizitonwose.calendarview.CalendarView.setHasBoundaries(CalendarView.kt:197)
        at com.kizitonwose.calendarviewsample.Example1Fragment$onViewCreated$4$$special$$inlined$doOnStart$1.onAnimationStart(Animator.kt:122)
        at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1048)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1110)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
        at com.kizitonwose.calendarviewsample.Example1Fragment$onViewCreated$4.onCheckedChanged(Example1Fragment.kt:192)
        at android.widget.CompoundButton.setChecked(CompoundButton.java:161)
        at android.widget.CompoundButton.toggle(CompoundButton.java:120)
        at android.widget.CompoundButton.performClick(CompoundButton.java:125)
        at android.view.View$PerformClick.run(View.java:21297)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5621)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

It seems that the issue was introduced by [this commit](https://github.com/kizitonwose/CalendarView/commit/f8919108ec68cc77daffbcd3e13842c2567d6288). Looks like changes made to the adapter data are not always immediately reflected by `calendarLayoutManager.findFirstVisibleItemPosition()`.

**Comment by kizitonwose** [comment]
Thank you for reporting this issue. It's now fixed in version [0.2.7](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.7)
